---
- name: Deploy mysql PV
  kubernetes.core.k8s: 
    state: absent
    src: "{{ mysql_pv_file }}"
- name: Destroy mysql PVC
  kubernetes.core.k8s:
    state: absent
    src: "{{ mysql_pvc_file }}"
- name: Destroy mysql
  kubernetes.core.k8s:
    state: absent
    src: "{{ mysql_deploy_file }}"
    wait: true
- name: Destroy mysql service
  kubernetes.core.k8s:
    state: absent
    src: "{{ mysql_service_file }}"
    wait: true