---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: default
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env: 
        - name: MYSQL_DATABASE
          value: "{{ mysql_database }}"
          #value: ghost-db
        - name: MYSQL_USER
          value: "{{ mysql_user }}"
          #value: ghost
        - name: MYSQL_PASSWORD
          value: "{{ mysql_password }}"
          #value: 123456
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true" 
        ports:
        - containerPort: "{{ mysql_ctn_port }}"
        #- containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      readinessProbe:
      exec:
        command:
        - mysqladmin ping --silent
      initialDelaySeconds: 5