---


- name: Permissoes para os dashboards
  shell: export GOOGLE_APPLICATION_CREDENTIALS=json/servicekey.json

- name: Dashboard CPU Utilization
  shell: gcloud monitoring dashboards create --config-from-file=monitoring/cpu.json

- name: Dashboard RAM
  shell: gcloud monitoring dashboards create --config-from-file=monitoring/ram.json

- name: Dashboard IO
  shell: gcloud monitoring dashboards create --config-from-file=monitoring/io.json
