---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: default
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: "{{ ghost_image }}"
        env:
        - name: url
          value: http://{{ ghost_ip }}:{{ ghost_port }}/
        - name: database__client
          value: "{{ mysql_client }}" 
        - name: database__connection__host
          value: "{{ mysql_host }}" 
        - name: database__connection__user
          value: "{{ mysql_user }}"
        - name: database__connection__password
          valueFrom:
                secretKeyRef:
                    name: mysql-secrets
                    key: password
        - name: database__connection__database
          value: "{{ mysql_database }}"
        - name: database__connection__port
          value: "{{ mysql_ctn_port }}"
        - name: mail__transport
          value: "SMTP"
        - name: mail__options__service
          value: "Mailgun"
        - name: mail__options__auth__user
          value: "{{ admin_user_name }}"
        - name: mail__options__auth__pass
          value: "{{ admin_password }}"
        ports:
        - containerPort: 2368