apiVersion: v1
kind: Service
metadata:
  name: ghost-service
spec:
  selector:
    app: ghost
  ports:
    - port: "{{ ghost_port }}"
      targetPort: 2368 #supostamente o servico ghost ouve sempre nesta porta
  type: LoadBalancer