apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: default
  labels:
    app: ghost
spec:
  type: LoadBalancer
  selector:
    app: ghost
  ports:
    - protocol: TCP  
      port: {{ ghost_port }} #80
      targetPort: 2368 #supostamente o servico ghost ouve sempre nesta porta
    #- protocol: TCP
    #  port: 80
    #  target: 2368
  loadBalancerIP: {{ ghost_ip }}