---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deploy
  namespace: default
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        env:
        - name: url
          value: http://{{ ghost_ip }}:{{ ghost_port }}/ 
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: mysql-service
        - name: database__connection__user
          value: ghost
        - name: database__connection__password
          value: pass
        - name: database__connection__database
          value: ghost-db
        ports:
        - containerPort: 2368