---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deploy
  namespace: default
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost
        env:
        - name: url
          value: http://{{ node_list.resources.0.status.addresses.1.address }}:30007/
        - name: db_client
          value: mysql
        - name: db_host
          value: mysql-service
        - name: db_user
          value: ghost
        - name: db_password
          value: password
        - name: db_database
          value: ghost-db
        ports:
        - containerPort: 2368