---
apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: default
  labels:
    app: ghost
spec:
  type: NodePort 
  selector:
    app: ghost
  ports:
    - targetPort: 2368 
      port: 2368 
      nodePort: 30007 