---

- name: Destroy ghost
  kubernetes.core.k8s:
    state: absent
    template: "{{ ghost_deploy_file }}"
    wait: true

- name: Destroy ghost service
  kubernetes.core.k8s:
    state: absent
    template: "{{ ghost_service_file }}"
    wait: true